#!/bin/sh

#size=5000

#for insert in L A B R S V
#do
#	for order in A P R
#	do
#		echo ""
#		if [ "$order" == "R" ]; then
#		    for number 1 2 3 4 5
#		    do
#		        seed=$RANDOM
#		        echo "Test: ./tlab $size $order $insert $seed"
#		        echo "t" | ./tlab $size $order $insert $seed | grep -v Tree
#		    done
#	    else
#		    echo "Test: ./tlab $size $order $insert"
#		    echo "t" | ./tlab $size $order $insert | grep -v Tree
#	    fi
#	done
#done



#!/bin/sh


size=200

for insert in L A B R S V
do
	for order in A 
	do
		echo ""
		echo "Test: ./tlab $size $order $insert"		
        echo "t" | ./tlab $size $order $insert | grep -v Tree
	done
done

